changelog:
  exclude:
    labels:
      # - skip-changelog
      - duplicate
      - invalid
      - wontfix
      - question
      - help wanted
      - good first issue

  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "🔧 Maintenance & Infrastructure"
      labels:
        - chore
        - ci
        - dependencies
    - title: "📚 Documentation"
      labels:
        - documentation
    - title: "📝 Other Changes"
      labels:
        - "*"